import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:timezone/data/latest_all.dart' as tz;

// Screens
import 'screens/patient_screen.dart';
import 'screens/guardian_screen.dart';
import 'auth/login_page.dart';
import 'auth/signup_page.dart';
import 'screens/patient_profile_page.dart';
import 'screens/guardian_profile_page.dart';
import 'screens/SplashScreen.dart'; // 👈 Splash screen import

// Firebase options (auto-generated by FlutterFire CLI)
import 'firebase_options.dart';

Future<void> requestPermissions() async {
  await [
    Permission.bluetooth,
    Permission.bluetoothConnect,
    Permission.bluetoothScan,
    Permission.location,
    Permission.notification
  ].request();
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await requestPermissions();
  tz.initializeTimeZones();
  runApp(const SaarthiApp());
}

class SaarthiApp extends StatelessWidget {
  const SaarthiApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SaarthiApp',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.indigo,
        useMaterial3: true,
      ),
      initialRoute: '/', // 👈 Start from splash screen
      routes: {
        '/': (context) => const SplashScreen(),
        '/login': (context) => const LoginPage(),
        '/signup': (context) => const SignupPage(),
        //'/patient_details': (context) => const PatientDetailsPage(),
        //'/guardian_details': (context) => const GuardianDetailsPage(),
        //'/patient': (context) => const PatientScreen(),
       // '/guardian': (context) => const GuardianScreen(),
        //'/patientProfile': (context) => const PatientProfilePage(),
        '/guardianProfile': (context) => const GuardianViewPage(),
      },
      onGenerateRoute: (settings) {
  if (settings.name == '/patient_screen') {
    final uid = settings.arguments as String;
    return MaterialPageRoute(
      builder: (context) => PatientScreen(uid: uid),
    );
  }
  if (settings.name == '/guardian_screen') {
    final uid = settings.arguments as String;
    return MaterialPageRoute(
      builder: (context) => GuardianScreen(uid: uid),
    );
  }
  if (settings.name == '/patientProfile') {
    final uid = settings.arguments as String;
    return MaterialPageRoute(
      builder: (context) => PatientProfilePage(uid: uid),
    );
  }

  return null;
},

    );
  }
}
